### ISSUE TITLE
Questions and Comments

### ISSUE THREAD

**Issue by unstoppablecarl** [singular1ty94/RogueJS#7]
Your game looks like a really good start. It would be nice to have a message log of the last few messages not just the latest one. 

I made a js roguelike micro-framework to help provide an organized structure and provide some basic  tools https://github.com/unstoppablecarl/js-roguelike-skeleton. I am trying to get feedback on the micro-framework from devs working on js roguelikes. As your game is a perfect candidate to use the famework I was hoping to get your feedback on it. I am still working on the docs so if you have any questions let me know.

Also let me know if you want any help with your project I would be more than happy to contribute.

**Comment by singular1ty94** [comment]
That's quite a nice and sophisticated framework, it seems to have taken away most of the low-level integration between the developer code and the ROT library itself, which is a good thing. ROT itself can be quite tiresome to work with, and I'm especially interested in your array2d and the entity behavior (like pushable). Some of the highlighting features, and mouse integration too, will immediately speed development along.

One thing I'm curious about - how to build on top of your entity framework to (obviously) make combat or pick-up events etc. Is that all done via prototyping when I construct my entity? For example:

```
RL.Entity.Types.zombie = {
    name: 'Zombie',
    char: 'z',
    color: 'red',
    bgColor: false,
    pushable: false,
    currentDirection: 'right',
    light_r: 100,
    light_g: 100,
    light_b: 255,

    bump: function(){
         //Calculate damages here..
    }
```

Otherwise, this framework looks fantastic, and I can honestly tell you that I will be changing over the disgusting mess of my own ROT engine towards your dev framework. It's a very nice job, and I think I'm one of the only JS roguelike developers out there (at least, we're very small compared to our traditional C/C++ or even Python fellows).

Sadly, I have a full-time uni degree that robs me of my developer time (creating WCF services hooray), but I will definitely be changing my engine over to yours, as I feel like I could benefit from may of your functions and features.

Thank you for developing such an awesome framework, and I will let you know how I go!

**Comment by unstoppablecarl** [comment]
The framework was designed for a beginner audience. So it purposefully does not have any object inheritance pattern. Adding one would not be difficult though. For entities it does implement a very simple pattern of copying functions/properties depending on the type (like the snippet you pasted).

I have not built in non-trivial opinionated entity-tile interactions (like combat or item pickup) because these things can vary dramatically in importance and implementation depending on the project. I do intend to make some examples of this in the docs sometime soon. 

Items on tiles could be implemented easily by making an Array2d object that manages the tile positions of items and updating the renderer to read and display them. You would basically duplicate the entity code for this.

DM me on twitter @unstoppableCarl and I will give you my contact info so we can chat if you like.
